spring:
  cache:
    type: caffeine
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/v1/item/**
          filters:
            - name: AuthenticationFilter
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN
                  - ROLE_MANAGER
                  - ROLE_SYSTEM
          metadata:
            public: true
        - id: category-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/v1/category/**
          filters:
            - name: AuthenticationFilter
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN
                  - ROLE_MANAGER
                  - ROLE_SYSTEM
          metadata:
            public: true
        - id: cart-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - name: AuthenticationFilter
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN
                  - ROLE_MANAGER
                  - ROLE_SYSTEM
          metadata:
            public: true
        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/sale/**
          filters:
            - name: AuthenticationFilter
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN
                  - ROLE_MANAGER
                  - ROLE_SYSTEM
          metadata:
            public: false
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          metadata:
            public: true
        - id: profile-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/profile/**
          metadata:
            public: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.cloud.gateway: ERROR

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024
