spring:
  cache:
    type: caffeine
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/v1/item/**
          filters:
          - name: AuthenticationFilter
            args:
              role: ROLE_USER
          metadata:
            public: true
        - id: category-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/api/v1/category/**
          filters:
          - name: AuthenticationFilter
            args:
              role: ROLE_USER
          metadata:
            public: true
        - id: cart-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
          - name: AuthenticationFilter
            args:
              role: ROLE_USER
          metadata:
            public: true
        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/sale/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ROLE_USER
          metadata:
            public: false
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
              - Path=/api/v1/auth/**
          metadata:
              public: true
        - id: profile-service
          uri: lb://AUTH-SERVICE
          predicates:
              - Path=/api/v1/profile/**
          metadata:
              public: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080